#!/bin/bash

# pwm_bowtie_wrapper: scan a genome with a PWM (using bowtie)
#  arguments:
#              matrix-file
#              p-value
#              bowtie-dir
#              genome-idx-file
#              assembly
#
#  25.11.2015  Giovanna Ambrosini

ARGS=5         # Script requires 5 arguments.
E_BADARGS=85   # Wrong number of arguments passed to script.

if [ $# -ne "$ARGS" ]
then
  echo "Usage: `basename $0` <matrix-file> <p-value> <bowtie-dir> <genome-idx-file> <assembly[hg19|mm9|..]>"
  exit $E_BADARGS
fi

# Declare associative array for background base composition
declare -A BGFREQ
BGFREQ[hg19]=0.29,0.21,0.21,0.29
BGFREQ[hg18]=0.29,0.21,0.21,0.29
BGFREQ[hg38]=0.29,0.21,0.21,0.29
BGFREQ[mm9]=0.29,0.21,0.21,0.29
BGFREQ[mm10]=0.29,0.21,0.21,0.29
BGFREQ[bosTau3]=0.29,0.21,0.21,0.29
BGFREQ[bosTau8]=0.29,0.21,0.21,0.29
BGFREQ[canFam2]=0.29,0.21,0.21,0.29
BGFREQ[canFam3]=0.29,0.21,0.21,0.29
BGFREQ[panTro2]=0.29,0.21,0.21,0.29
BGFREQ[panTro5]=0.29,0.21,0.21,0.29
BGFREQ[rn5]=0.28,0.22,0.22,0.28
BGFREQ[rn6]=0.28,0.22,0.22,0.28
BGFREQ[dm3]=0.29,0.21,0.21,0.29
BGFREQ[dm6]=0.29,0.21,0.21,0.29
BGFREQ[ce6]=0.32,0.18,0.18,0.32
BGFREQ[ce10]=0.32,0.18,0.18,0.32
BGFREQ[ce11]=0.32,0.18,0.18,0.32
BGFREQ[danRer5]=0.32,0.18,0.18,0.32
BGFREQ[danRer7]=0.32,0.18,0.18,0.32
BGFREQ[danRer10]=0.32,0.18,0.18,0.32
BGFREQ[sacCer2]=0.31,0.19,0.19,0.31
BGFREQ[sacCer3]=0.31,0.19,0.19,0.31

echo "BG nucleotide composition: ${BGFREQ[$5]}"
bg_freq=${BGFREQ[$5]}

chrNC_dir=/home/local/db/genome

if [ -f "$1" ]
then
    matrix_file=$1
else
    echo "File \"$1\" does not exist."
    exit $E_BADARGS
fi

p_value=$2
bowtie_dir=$3

if [ -f "$3/$4.1.ebwt" ]
then
    genome_idx_file=$4
else
    echo "File \"$3/$4.1.ebwt\" does not exist."
    exit $E_BADARGS
fi

assembly=$5

# Extract basename from matrix file (without path)
matrix_name=$(basename "$matrix_file")
extension="${matrix_name##*.}"
matrix_name="${matrix_name%.*}"

echo "PWM name: $matrix_name"

echo "========               Computing PWM length                ========"
matrix_len=$(cat $matrix_file | perl -ane 'next if (/^#/ or /^>/); print;' | wc -l)

file_len=$(cat $matrix_file | wc -l)

if [ $file_len -gt $matrix_len ]
then
    sed 1d $matrix_file > $matrix_file".tmp"
    matrix_file=$matrix_file".tmp"
fi

echo "PWM file: $matrix_file"
echo "PWM length: $matrix_len"
echo "PWM file length : $file_len lines"

echo "========               Calculating PWM score               ========"
matrix_score=$(matrix_prob -e $p_value --bg "$bg_freq" $matrix_file \
	| grep SCORE | sed 's/:/\ /'\
	| awk -F " " '{print $2}')

echo "PWM score: $matrix_score"

# Run Bowtie pipeline
pwmout_bed=${matrix_name}_co${matrix_score}_bowtie.bed

echo "========               Bowtie-based pipeline               ========"
echo "mba -c $matrix_score -l $matrix_len $matrix_file | sort -k2,2 -nr | awk '{print \">\"\$2\"\n\"\$1}' | bowtie --threads 4 -l $matrix_len -n0 -a $bowtie_dir/$genome_idx_file -f - --un unmapped.dat | sort -s -k3,3 -k4,4n | bowtie2bed -s $assembly -l $matrix_len -i $chrNC_dir > $pwmout_bed" 
echo "..."
mba -c $matrix_score -l $matrix_len $matrix_file | sort -k2,2 -nr | awk '{print ">"$2"\n"$1}' | bowtie --threads 4 -l $matrix_len -n0 -a $bowtie_dir/$genome_idx_file -f - --un unmapped.dat | sort -s -k3,3 -k4,4n | bowtie2bed -s $assembly -l $matrix_len -i $chrNC_dir > $pwmout_bed

echo "List of matches (BED format) : $pwmout_bed"

rm unmapped.dat
